# Generated by Django 6.0.1 on 2026-01-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='플랫폼명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='코드')),
                ('logo_url', models.URLField(blank=True, verbose_name='로고 URL')),
                ('website_url', models.URLField(blank=True, verbose_name='공식 웹사이트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '플랫폼',
                'verbose_name_plural': '플랫폼',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='시청 가능')),
                ('link_url', models.URLField(blank=True, verbose_name='시청 링크')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트일')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='contents.content', verbose_name='콘텐츠')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='platforms.platform', verbose_name='플랫폼')),
            ],
            options={
                'verbose_name': '시청 가능 정보',
                'verbose_name_plural': '시청 가능 정보',
                'unique_together': {('content', 'platform')},
            },
        ),
    ]
