# Generated by Django 6.0.1 on 2026-01-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목 (한글)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='제목 (영문)')),
                ('content_type', models.CharField(choices=[('movie', '영화'), ('drama', '드라마')], max_length=20, verbose_name='콘텐츠 유형')),
                ('tmdb_id', models.IntegerField(unique=True, verbose_name='TMDb ID')),
                ('poster_url', models.URLField(blank=True, verbose_name='포스터 URL')),
                ('backdrop_url', models.URLField(blank=True, verbose_name='배경 이미지 URL')),
                ('overview', models.TextField(blank=True, verbose_name='줄거리')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='개봉/방영일')),
                ('rating', models.FloatField(default=0, verbose_name='TMDb 평점')),
                ('vote_count', models.IntegerField(default=0, verbose_name='평점 참여수')),
                ('popularity', models.FloatField(default=0, verbose_name='인기도')),
                ('runtime', models.IntegerField(blank=True, null=True, verbose_name='러닝타임 (분)')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='감독')),
                ('cast', models.JSONField(blank=True, default=list, verbose_name='출연진')),
                ('is_adult', models.BooleanField(default=False, verbose_name='성인물 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '콘텐츠',
                'verbose_name_plural': '콘텐츠',
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='장르명')),
                ('tmdb_id', models.IntegerField(unique=True, verbose_name='TMDb ID')),
            ],
            options={
                'verbose_name': '장르',
                'verbose_name_plural': '장르',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcaster', models.CharField(blank=True, max_length=50, verbose_name='방송사')),
                ('air_day', models.CharField(blank=True, max_length=20, verbose_name='방영 요일')),
                ('air_time', models.TimeField(blank=True, null=True, verbose_name='방영 시간')),
                ('episode_count', models.IntegerField(default=0, verbose_name='총 회차')),
                ('current_episode', models.IntegerField(default=0, verbose_name='현재 회차')),
                ('status', models.CharField(choices=[('airing', '방영중'), ('ended', '완결'), ('upcoming', '방영예정')], default='airing', max_length=20, verbose_name='상태')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drama_info', to='contents.content', verbose_name='콘텐츠')),
            ],
            options={
                'verbose_name': '드라마 정보',
                'verbose_name_plural': '드라마 정보',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='genres',
            field=models.ManyToManyField(blank=True, to='contents.genre', verbose_name='장르'),
        ),
        migrations.CreateModel(
            name='YouTubeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, verbose_name='YouTube 영상 ID')),
                ('title', models.CharField(max_length=200, verbose_name='영상 제목')),
                ('channel_name', models.CharField(max_length=100, verbose_name='채널명')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='썸네일 URL')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('is_featured', models.BooleanField(default=False, verbose_name='추천 리뷰')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='게시일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_reviews', to='contents.content', verbose_name='콘텐츠')),
            ],
            options={
                'verbose_name': '유튜브 리뷰',
                'verbose_name_plural': '유튜브 리뷰',
                'ordering': ['-is_featured', '-view_count'],
            },
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['-popularity'], name='contents_co_popular_c59499_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['-release_date'], name='contents_co_release_93be42_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type', '-popularity'], name='contents_co_content_a5b254_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['tmdb_id'], name='contents_co_tmdb_id_c93297_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='youtubereview',
            unique_together={('content', 'video_id')},
        ),
    ]
