import { Content, Genre, YouTubeReview } from '@/types/content';

export const mockGenres: Genre[] = [
  { id: 1, name: '액션', tmdb_id: 28 },
  { id: 2, name: '코미디', tmdb_id: 35 },
  { id: 3, name: '드라마', tmdb_id: 18 },
  { id: 4, name: 'SF', tmdb_id: 878 },
  { id: 5, name: '로맨스', tmdb_id: 10749 },
];

export const mockMovies: Content[] = [
  {
    id: 1,
    title: '파묘',
    title_en: 'Exhuma',
    content_type: 'movie',
    poster_url: 'https://image.tmdb.org/t/p/w500/eH9XHJmGO8i7NJWU3p3J9JxwLel.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/eH9XHJmGO8i7NJWU3p3J9JxwLel.jpg',
    overview: '미국 LA, 거액의 의뢰를 받은 무당 화림과 봉길은 기이한 병이 대물림되는 집안의 장손을 만난다.',
    release_date: '2024-02-22',
    rating: 8.2,
    popularity: 95.5,
    runtime: 134,
    director: '장재현',
    cast: ['최민식', '김고은', '유해진', '이도현'],
    genres: [mockGenres[0], mockGenres[2]],
  },
  {
    id: 2,
    title: '범죄도시 4',
    title_en: 'The Roundup: Punishment',
    content_type: 'movie',
    poster_url: 'https://image.tmdb.org/t/p/w500/aK6lX5pLAhWqfEbgWLXOHx17Nwd.jpg',
    overview: '괴물형사 마석도가 신종 온라인 범죄 조직과 맞서 싸운다.',
    release_date: '2024-04-24',
    rating: 7.8,
    popularity: 88.2,
    runtime: 109,
    director: '허명행',
    cast: ['마동석', '김무열', '박지환'],
    genres: [mockGenres[0], mockGenres[1]],
  },
  {
    id: 3,
    title: '듄: 파트 2',
    title_en: 'Dune: Part Two',
    content_type: 'movie',
    poster_url: 'https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
    overview: '폴 아트레이데스가 프레멘과 함께 하코넨에 맞서 싸운다.',
    release_date: '2024-02-28',
    rating: 8.5,
    popularity: 92.1,
    runtime: 166,
    director: '드니 빌뇌브',
    cast: ['티모시 샬라메', '젠데이아', '레베카 퍼거슨'],
    genres: [mockGenres[3], mockGenres[0]],
  },
  {
    id: 4,
    title: '쿵푸팬더 4',
    title_en: 'Kung Fu Panda 4',
    content_type: 'movie',
    poster_url: 'https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg',
    overview: '드래곤 워리어 포가 새로운 악당과 맞서 싸운다.',
    release_date: '2024-03-08',
    rating: 7.2,
    popularity: 78.5,
    runtime: 94,
    director: '마이크 미첼',
    cast: ['잭 블랙', '어콰피나'],
    genres: [mockGenres[1], mockGenres[0]],
  },
  {
    id: 5,
    title: '오펜하이머',
    title_en: 'Oppenheimer',
    content_type: 'movie',
    poster_url: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    overview: '원자폭탄 개발을 이끈 물리학자 로버트 오펜하이머의 이야기.',
    release_date: '2023-07-21',
    rating: 8.4,
    popularity: 85.3,
    runtime: 180,
    director: '크리스토퍼 놀란',
    cast: ['킬리언 머피', '에밀리 블런트', '로버트 다우니 주니어'],
    genres: [mockGenres[2], mockGenres[0]],
  },
  {
    id: 6,
    title: '가디언즈 오브 갤럭시 Vol.3',
    title_en: 'Guardians of the Galaxy Vol. 3',
    content_type: 'movie',
    poster_url: 'https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
    overview: '가디언즈가 로켓의 과거를 마주하며 마지막 모험을 떠난다.',
    release_date: '2023-05-03',
    rating: 8.0,
    popularity: 82.1,
    runtime: 150,
    director: '제임스 건',
    cast: ['크리스 프랫', '조 샐다나', '브래들리 쿠퍼'],
    genres: [mockGenres[0], mockGenres[3]],
  },
];

export const mockDramas: Content[] = [
  {
    id: 101,
    title: '눈물의 여왕',
    title_en: 'Queen of Tears',
    content_type: 'drama',
    poster_url: 'https://image.tmdb.org/t/p/w500/cTsAZ5WJsjTbKSdLGO7swhPJplz.jpg',
    overview: '재벌가의 여왕과 그녀의 남편이 위기를 극복해 나가는 이야기.',
    release_date: '2024-03-09',
    rating: 8.8,
    popularity: 98.5,
    genres: [mockGenres[2], mockGenres[4]],
  },
  {
    id: 102,
    title: '선재 업고 튀어',
    title_en: 'Lovely Runner',
    content_type: 'drama',
    poster_url: 'https://image.tmdb.org/t/p/w500/7i1cKoLUl7x4XfGxKb9Cjgxc3gT.jpg',
    overview: '과거로 돌아가 첫사랑을 구하려는 여자의 이야기.',
    release_date: '2024-04-08',
    rating: 9.1,
    popularity: 96.2,
    genres: [mockGenres[4], mockGenres[2]],
  },
  {
    id: 103,
    title: '정년이',
    title_en: 'Jeongnyeon: The Star is Born',
    content_type: 'drama',
    poster_url: 'https://image.tmdb.org/t/p/w500/A53bO3pInGTyPwV5zPvzLKM3Yxr.jpg',
    overview: '일제강점기 기생들의 이야기.',
    release_date: '2024-10-12',
    rating: 8.5,
    popularity: 89.3,
    genres: [mockGenres[2]],
  },
  {
    id: 104,
    title: '무빙',
    title_en: 'Moving',
    content_type: 'drama',
    poster_url: 'https://image.tmdb.org/t/p/w500/bKsxJ8ChE8xGS2fOSs0GL98j0qH.jpg',
    overview: '초능력을 숨기고 살아가는 아이들과 그들의 부모 이야기.',
    release_date: '2023-08-09',
    rating: 8.9,
    popularity: 94.1,
    genres: [mockGenres[0], mockGenres[3]],
  },
  {
    id: 105,
    title: '이상한 변호사 우영우',
    title_en: 'Extraordinary Attorney Woo',
    content_type: 'drama',
    poster_url: 'https://image.tmdb.org/t/p/w500/3deMHEuKpkZV3nYOSFNRi7PLpNH.jpg',
    overview: '자폐 스펙트럼을 가진 천재 변호사의 성장 이야기.',
    release_date: '2022-06-29',
    rating: 8.7,
    popularity: 91.5,
    genres: [mockGenres[2], mockGenres[1]],
  },
  {
    id: 106,
    title: '더 글로리',
    title_en: 'The Glory',
    content_type: 'drama',
    poster_url: 'https://image.tmdb.org/t/p/w500/ea4T78MQDV4WfOFU0iKnzoQmRY7.jpg',
    overview: '학교 폭력 피해자의 처절한 복수극.',
    release_date: '2022-12-30',
    rating: 8.6,
    popularity: 93.8,
    genres: [mockGenres[2]],
  },
];

export const mockTrending = [...mockMovies.slice(0, 3), ...mockDramas.slice(0, 3)];
export const mockNewReleases = [...mockDramas.slice(0, 2), ...mockMovies.slice(0, 4)];

// YouTube 리뷰 Mock 데이터
export const mockYouTubeReviews: Record<number, YouTubeReview[]> = {
  1: [ // 파묘
    {
      id: 1,
      video_id: 'abc123',
      title: '[스포주의] 파묘 완벽 해석 - 숨겨진 의미와 복선 총정리',
      channel_name: '영화리뷰채널',
      thumbnail_url: 'https://i.ytimg.com/vi/abc123/maxresdefault.jpg',
      view_count: 1520000,
      is_featured: true,
      published_at: '2024-03-01T10:00:00Z',
      youtube_url: 'https://www.youtube.com/watch?v=abc123',
    },
    {
      id: 2,
      video_id: 'def456',
      title: '파묘가 천만 간 이유 - 한국 호러의 새 역사',
      channel_name: '씨네타운',
      thumbnail_url: 'https://i.ytimg.com/vi/def456/maxresdefault.jpg',
      view_count: 890000,
      is_featured: false,
      published_at: '2024-03-15T14:30:00Z',
      youtube_url: 'https://www.youtube.com/watch?v=def456',
    },
    {
      id: 3,
      video_id: 'ghi789',
      title: '파묘 결말 해석 & 쿠키영상 분석',
      channel_name: '무비토크',
      thumbnail_url: 'https://i.ytimg.com/vi/ghi789/maxresdefault.jpg',
      view_count: 650000,
      is_featured: false,
      published_at: '2024-03-10T09:00:00Z',
      youtube_url: 'https://www.youtube.com/watch?v=ghi789',
    },
  ],
  101: [ // 눈물의 여왕
    {
      id: 4,
      video_id: 'jkl012',
      title: '눈물의 여왕 1-8화 몰아보기 리뷰 (김수현x김지원 케미 미쳤다)',
      channel_name: '드라마딕',
      thumbnail_url: 'https://i.ytimg.com/vi/jkl012/maxresdefault.jpg',
      view_count: 2100000,
      is_featured: true,
      published_at: '2024-04-01T12:00:00Z',
      youtube_url: 'https://www.youtube.com/watch?v=jkl012',
    },
    {
      id: 5,
      video_id: 'mno345',
      title: '눈물의 여왕 결말 예측 - 해피엔딩일까?',
      channel_name: '드라마리뷰어',
      thumbnail_url: 'https://i.ytimg.com/vi/mno345/maxresdefault.jpg',
      view_count: 1350000,
      is_featured: false,
      published_at: '2024-04-20T18:00:00Z',
      youtube_url: 'https://www.youtube.com/watch?v=mno345',
    },
  ],
  102: [ // 선재 업고 튀어
    {
      id: 6,
      video_id: 'pqr678',
      title: '선재 업고 튀어가 역대급인 이유 - 타임슬립 로맨스의 정석',
      channel_name: '드라마딕',
      thumbnail_url: 'https://i.ytimg.com/vi/pqr678/maxresdefault.jpg',
      view_count: 1800000,
      is_featured: true,
      published_at: '2024-05-01T10:00:00Z',
      youtube_url: 'https://www.youtube.com/watch?v=pqr678',
    },
  ],
};

// 콘텐츠 ID로 리뷰 가져오기
export function getMockReviews(contentId: number): YouTubeReview[] {
  return mockYouTubeReviews[contentId] || [];
}
